name: Continuous integration
on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build:
    strategy:
      matrix:
        os: ['ubuntu-latest']
    runs-on: ${{ matrix.os }}
    name: Default GHC on ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v23
    - name: Build
      run: |
        nix build \
          --accept-flake-config \
          --print-build-logs \
          .
